### ISSUE TITLE
Make Restrict() future-proof

### ISSUE THREAD

**Issue by gnoack** [gnoack/golandlock#4]
This package does not provide stability guarantees yet, and we need to fix the API so that we can provide these guarantees.

Things I'd like to fix:
 * **Arguments:** When calling Restrict, it's difficult to tell apart which of the arguments is which. They all have the same type.
 * **Flexibility:** There is little flexibility to use different sets of permissions other than the four built-in ones. (Also see bug #3)
 * **Future Landlock compatibility:** The backwards compatibility story for future versions of Landlock is unclear: To make sure that calling programs don't break when golandlock starts supporting a future Landlock ABI v2, callers will need to take action to update to new versions at some point.
 * **Old kernel compatibility:** The backwards compatibility story for older kernels is unclear: As @l0kod pointed out, as soon as Landlock will have multiple ABI levels, there will be a use case for graceful degradation on old kernels, where the `Restrict()` call should lock permissions down as much as possible given the kernel that it's running on. Other users might want to still fail in that case though.

**Prior art for backwards compatibility:**
@l0kod's [rust-landlock](https://github.com/landlock-lsm/rust-landlock/blob/master/src/lib.rs) supports multiple backwards compatibility strategies. (See [ErrorThreshold enum](https://github.com/landlock-lsm/rust-landlock/blob/master/src/lib.rs#L94))

**Comment by gnoack** [comment]
## Future Landlock Compatibility

**Main risk:** Migrating from Landlock ABI N to ABI N+1 could lock down the calling process more than originally intended.

Migration between Landlock ABIs should therefore be explicit, as it can be a potentially breaking change.

I assume that for most users it should not break in practice though... the use cases I've come across often only rely on basic file operations, which are already supported in Landlock V1.

### Option A: Use Go module versioning to track Landlock ABI versions

We could make the Go module version be the same as the used Landlock ABI version.

Go packages are supposed to give compatibility guarantees within major versions ([doc](https://golang.org/doc/modules/developing#versioning)), but an upgrade between major versions is a step where library users are naturally supposed to double check that it keeps working.

Pros:
 * Requires no explicit concept of ABI version at the code layer. This would be good, because in the long run, the feature set should stabilize anyway, and then it's just baggage to make things so explicit.

### Option B: Ask users to pass their desired ABI version

**Comment by gnoack** [comment]
# Old kernel compatibility

The scenario is that `Restrict()` is called on a kernel that has an older version of Landlock, or where Landlock is not supported.

The use cases I know of are:
* **Graceful downgrade**: For software whose authors do not control the deployment environment, e.g. desktop software.
* **Strict mode**: For software whose authors want the security and control the deployment environment enough to know that Landlock is installed at the required version.

**Comment by gnoack** [comment]
I consider the above CL to be OK for fixing the "arguments" and "flexibility" concerns.

**Comment by gnoack** [comment]
I consider backwards and forwards-compatibility to be appropriately addressed with these changes.

**Comment by l0kod** [comment]
> Main risk: Migrating from Landlock ABI N to ABI N+1 could lock down the calling process more than originally intended.
>
> Migration between Landlock ABIs should therefore be explicit, as it can be a potentially breaking change.

Just to be clear, future (kernel) Landlock versions will always be compatible with older versions (e.g. the default behavior or implicit options will never change). This is required for (simple) backward compatibility (i.e. by avoiding user space to give an ABI version to the kernel) and to get a deterministic access-control.

**Comment by l0kod** [comment]
Comment about `AccessFSRoughlyRead`: https://github.com/gnoack/golandlock/commit/f6bba1285ffd2c64b2b8774876c29c62213d1e5a#r53543969

**Comment by l0kod** [comment]
Comment about `VMax`: https://github.com/gnoack/golandlock/commit/da2b49f57ce238379d93496f1c3ed843125e7536#r53544451
